[project]
name = "peshitta-cj"
version = "0.0.0"
description = "A collection of tools and scripts to categorise Peshitta verses into Jewish and Christian authorship"
authors = [
    {name = "Ryosuke Nagata",email = "r.nagata.21@abdn.ac.uk"}
]
license = {text = "BSD-2-Clause"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn (>=1.6.1,<2.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "text-fabric (>=13.0.6,<14.0.0)",
    "nltk (>=3.9.1,<4.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "jsonschema (>=4.23.0,<5.0.0)",
    "tokenizers (>=0.21.1,<0.22.0)",
    "transformers (>=4.51.1,<5.0.0)",
    "datasets (>=3.5.0,<4.0.0)",
    "torch (>=2.6.0,<3.0.0)",
    "torchvision (>=0.21.0,<0.22.0)",
    "torchaudio (>=2.6.0,<3.0.0)",
    "datasets (>=3.5.0,<4.0.0)",
    "lime (>=0.2.0.1,<0.3.0.0)",
    "flask (>=3.1.0,<4.0.0)",
    "beautifulsoup4 (>=4.13.4,<5.0.0)"
]

[tool.poetry]
packages = [
    { include = "src" }
]

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.4"
pytest = "^8.3.5"
interrogate = "^1.7.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

# pytest configurations
[tool.pytest.ini_options]
pythonpath = [".", "src"]
addopts = [
    "--import-mode=importlib",
]

# Ruff configurations
[tool.ruff]
line-length = 80

# Assume Python 3.12.
target-version = "py312"

[tool.ruff.format]
skip-magic-trailing-comma = false
line-ending = "lf"

# Like Black:
# use double quotes for strings.
quote-style = "double"
# indent with spaces, rather than tabs.
indent-style = "space"
# format docstrings
docstring-code-format = true

[tool.ruff.lint]
# Enable all rules by default
select = ["ALL"]
# exclude specific rules
ignore = [
    "ANN201",  # missing-return-type-undocumented-public-function
    "ANN204",  # missing-return-type-special-method
    "COM812",  # missing-trailing-comma
    "D105",    # undocumented-magic-method
    "D107",    # undocumented-public-init
    "D203",    # one-blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "D403",    # first-line-capitalized
    "D415",    # missing-terminal-punctuation
    "ERA001",  # commented-out-code
    "ISC003",  # explicit-string-concatenation
    "N803",    # invalid-argument-name
    "PERF401", # manual-list-comprehension
    "PLR2004", # magic-value-comparison
    "T201",    # print
    ]

# List of rules to apply when autofix is applied
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"test/*" = [
    "CPY001", # missing-copyright-notice
    "E402",   # module-import-not-at-top-of-file
    "D101",   # undocumented-public-class
    "D102",   # undocumented-public-method
    "D103",   # undocumented-public-function
    "PLR0913",# too-many-arguments
    "PLR6301",# no-self-use
    "S101",   # assert
    "SLF001"
    ]
