[project]
name = "peshitta-cj"
version = "0.0.0"
description = "A collection of tools and scripts to categorise Peshitta verses into Jewish and Christian authorship"
authors = [
    {name = "Ryohskay",email = "r.nagata.21@abdn.ac.uk"}
]
license = {text = "BSD-2-Clause"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn (>=1.6.1,<2.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "text-fabric (>=13.0.6,<14.0.0)"
]

[tool.poetry]
packages = [
    { include = "classifier" },
    { include = "scraper" }
]

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.4"
pytest = "^8.3.5"
interrogate = "^1.7.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

# Ruff configurations
[tool.ruff]
# Enable all rules by default
select = ["ALL"]
# exclude specific rules
ignore = [
    "ANN101",  # missing-type-self
    "ANN204",  # missing-return-type-special-method
    "COM812",  # missing-trailing-comma
    "CPY001",  # missing-copyright-notice
    "D105",    # undocumented-magic-method
    "D107",    # undocumented-public-init
    "D203",    # one-blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "D403",    # first-line-capitalized
    "DOC501",  # docstring-missing-exception
    "DOC502",  # docstring-extraneous-exception
    "ERA001",  # commented-out-code
    "ISC003",  # explicit-string-concatenation
    "PLR2004", # magic-value-comparison
    "TID252",  # relative-imports
    "T201",    # print
    ]

# List of rules to apply when autofix is applied
fixable = ["ALL"]
unfixable = []

line-length = 80

# Assume Python 3.12.
target-version = "py312"

[tool.ruff.format]
skip-magic-trailing-comma = false
line-ending = "lf"

# Like Black:
# use double quotes for strings.
quote-style = "double"
# indent with spaces, rather than tabs.
indent-style = "space"

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = [
    "E402",  # module-import-not-at-top-of-file
    "ANN001",
    "ANN201",
    "D100",
    "D103",
    "D205",
    "D400",
    "D401",
    "S101"
    ]
